# Generated by Django 3.0.5 on 2021-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyoffer',
            name='offer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
