# Generated by Django 3.0.5 on 2021-02-13 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyoffer',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
